import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import About from "./components/About";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aadil's Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-slate-300 dark:bg-black mx-4 md:mx-16`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <About />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
